### ISSUE TITLE
Please consider adding a `pbm_pitr_enabled` variable

### ISSUE THREAD

**Issue by sleto-it** [percona/mongo_terraform_ansible#77]
My analysis (can be wrong):

In ansible's`all` file:

```
###############
## Backup
###############

pbmuser: pbm
pbmpwd: secretpwd
pbm_backup_type: physical
pbm_retention_days: 3
pbm_backup_hour: 0
pbm_backup_minute: 2
pbm_purge_hour: 0
pbm_purge_minute: 2
pbm_os_user: mongod
pbm_pitr_enabled: yes <--- define variable and default value here
```

In terraform's `main`:

```
- name: configure backup process
  hosts: rs*:cfg*
  tags: backup
  become: true
  tasks:
    - name: set up storage location for PBM
      shell: pbm config --file /etc/pbm-storage.conf --mongodb-uri '{{ mongodb_uri }}'  add here --set pitr.enabled={{ pbm_pitr_enabled }}
      when: mongodb_primary is defined and mongodb_primary
```

For the docker case, probably in `pre-creation` file (?):

```
locals {
  storage_config_content = templatefile("${path.module}/pbm-storage.tmpl", {
    minio_region     = var.minio_region
    bucket_name      = var.bucket_name
    cluster_name     = var.cluster_name
    minio_server     = var.minio_server
    minio_port       = var.minio_port
    minio_access_key = var.minio_access_key
    minio_secret_key = var.minio_secret_key
    pitr:
      enabled: var.pbm_pitr_enabled <--- (?)  
  })
}
```

or in `pbm-storage.tmpl`

Thanks!
